lang = {
    "EN": {
        "index": {
            "country code": "en",
            "tab title": "Holiday Home in Rome",
            "description": "Enjoy The Comfort Of Your Holiday Home In The Garbatella District - The Ideal Place To Stay In Rome",
            "supported languages": ["EN", "IT"],
            "header title": "Enjoy The Comfort Of Your Holiday Home",
            "header subtitle": "The Perfect Place To Stay In Rome",
            "book button": "BOOK NOW",
            "home": "HOME",
            "living": "1 Spacious Living Room",
            "bed room": "2 Comfortable Double Rooms",
            "bathroom": "1 Welcoming Bathroom",
            "kitchen": "1 Equipped Kitchen",
            "terrace": "2 Silent Terraces",
            "free wifi": "Free Unlimited Wifi",
            "district": "DISTRICT",
            "supermarket": "Supermarket In Front Of Home",
            "paid garage": "Paid Garage Under The Home",
            "tobacco shop": "Tobacconist 10m Away",
            "cafe": "Bar In The Same Street 100m",
            "metro": "Garbatella Metro 10min Walk",
            "city center": "City Center Less Than 20min",
            "prohibited": "PROHIBITED",
            "no smoke": "No Smoking Inside",
            "no party": "No Loud Parties",
            "contact": "CONTACT",
            "tourist tax": "Pay The Tourist Tax"
        },
        "book-holiday-home": {
            "country code": "en",
            "tab title": "Book Your Holiday Home",
            "description": "Enjoy The Comfort Of Your Holiday Home In The Garbatella District - The Ideal Place To Stay In Rome",
            "supported languages": ["EN", "IT"],
            "name": "NAME",
            "surname": "SURNAME",
            "email": "EMAIL",
            "codes": ["1", "39"],
            "phone": "PHONE",
            "select days": "SELECT DAYS",
            "guests no.": "GUESTS NO. (max. 4)",
            "submit": "BOOK",
            "date format": "Y/m/d"
        },
        "tourist-tax-payment": {
            "country code": "en",
            "tab title": "Tourist Tax",
            "description": "Choose the payment method you prefer to pay the tourist tax",
            "supported languages": ["EN", "IT"],
            "info": "6 Euros Per Night At Person (No Children Under 12)",
            "or": "OR",
            "credit card": "CREDIT CARD"
        }
    },
    "IT": {
        "index": {
            "country code": "it",
            "tab title": "Casa Vacanze a Roma",
            "description": "Goditi Il Comfort Della Tua Casa Vacanze Nel Quartiere Garbatella - Il Luogo Ideale Per Soggiornare A Roma",
            "supported languages": ["IT", "EN"],
            "header title": "Goditi Il Comfort Della Tua Casa Vacanza",
            "header subtitle": "Il Luogo Ideale Per Soggiornare A Roma",
            "book button": "PRENOTA ORA",
            "home": "CASA",
            "living": "1 Soggiorno Spazioso",
            "bed room": "2 Comode Camere Matrimoniali",
            "bathroom": "1 Bagno Accogliente",
            "kitchen": "1 Cucina Accessoriata",
            "terrace": "2 Sileziosi Terrazzi",
            "free wifi": "Wifi Gratuito Illimitato",
            "district": "QUARTIERE",
            "supermarket": "Supermercato Di Fronte Casa",
            "paid garage": "Garage a Pagamento Sotto Casa",
            "tobacco shop": "Tabaccheria a 10m",
            "cafe": "Bar Nella Stessa Via a 100m",
            "metro": "Metro Garbatella 10min a Piedi",
            "city center": "In Centro In Meno Di 20min",
            "prohibited": "DIVIETI",
            "no smoke": "Vietato Fumare All'Interno",
            "no party": "Vietate Feste Rumorose",
            "contact": "CONTATTO",
            "tourist tax": "Paga La Tassa Di Soggiorno"
        },
        "book-holiday-home": {
            "country code": "it",
            "tab title": "Prenota La Tua Casa Vacanze",
            "description": "Goditi Il Comfort Della Tua Casa Vacanze Nel Quartiere Garbatella - Il Luogo Ideale Per Soggiornare A Roma",
            "supported languages": ["IT", "EN"],
            "name": "NOME",
            "surname": "COGNOME",
            "email": "EMAIL",
            "codes": ["39", "1"],
            "phone": "TELEFONO",
            "select days": "SELEZIONA GIORNI",
            "guests no.": "N° OSPITI (max. 4)",
            "submit": "PRENOTA",
            "date format": "d/m/Y"
        },
        "tourist-tax-payment": {
            "country code": "it",
            "tab title": "Tassa Di Soggiorno",
            "description": "Scegli il metodo di pagamento che preferisci per pagare la tassa di soggiorno",
            "supported languages": ["IT", "EN"],
            "info": "6 Euro a Notte a Persona (No Minori Di 12 Anni)",
            "or": "OPPURE",
            "credit card": "CARTA DI CREDITO"
        }
    }
}