lang = {
    "EN": {
        "index": {
            "country code": "en",
            "tab title": "Holiday home in Rome",
            "description": "Enjoy the comfort of your holiday home in the Garbatella neighborhood - The ideal place to stay in Rome",
            "tourist tax": "Pay the tourist tax",
            "supported languages": ["EN", "IT"],
            "header title": "Garbatella Elegant Apartment",
            "header subtitle": "The perfect place to stay in Rome",
            "book button": "BOOK NOW",
            "home": "HOME",
            "mq": "100mq",
            "elevator": "Elevator",
            "living room": "1 Spacious living room",
            "bed room": "2 Double rooms",
            "bathroom": "1 Welcoming bathroom",
            "kitchen": "1 Equipped kitchen",
            "terrace": "2 Silent terraces",
            "services": "SERVICES",
            "dishwasher": "Dishwasher",
            "fridge": "Fridge",
            "microwave oven": "Microwave oven",
            "toaster": "Toaster",
            "laundry machine": "Laundry machine",
            "clothesline": "Clothesline",
            "hairdryer": "Hairdryer",
            "netflix": "40inch HDTV with Netflx",
            "conditioner": "Conditioner hot/cold",
            "wifi": "Free unlimited wifi",
            "fire alarm": "Fire alarm",
            "fire extinguisher": "Fire extinguisher",
            "first aid kit": "First aid Kit",
            "neighborhood": "NEIGHBORHOOD",
            "supermarket": "Supermarket in front of the Home",
            "garage": "Hourly garage under the Home",
            "parking": "Free parking along the street",
            "tobacco shop": "Tobacconist 10m away",
            "cafe": "Bar in the same street at 100m",
            "metro": "Garbatella metro 10min walk",
            "city center": "City center less than 20min",
            "rules": "RULES",
            "smoking": "Smoking only on terraces",
            "no party": "No loud parties",
            "contact": "CONTACT",
            "always available": "Host is always available to help",
            "more": "MORE..."
        },
        "more": {
            "country code": "en",
            "tab title": "Holiday home in Rome",
            "description": "Enjoy the comfort of your holiday home in the Garbatella neighborhood - The ideal place to stay in Rome",
            "supported languages": ["EN", "IT"],
            "apartment": "Apartment",
            "neighborhood": "Neighborhood",
            "garbatella": "What to see in Garbatella",
            "keep in mind": "To keep In Mind"
        },
        "book-holiday-home": {
            "country code": "en",
            "tab title": "Book your holiday home",
            "description": "Enjoy the comfort of your holiday home in the Garbatella neighborhood - The ideal place to stay in Rome",
            "supported languages": ["EN", "IT"],
            "name": "NAME",
            "surname": "SURNAME",
            "email": "EMAIL",
            "codes": [
                "1", "93", "355", "213", "1-684", "376", "244", "1-264", "672", "1-268", "54",
                "374", "297", "61", "43", "994", "1-242", "973", "880", "1-246", "375",
                "32", "501", "229", "1-441", "975", "591", "387", "267", "55", "246",
                "673", "359", "226", "257", "855", "237", "238", "1-345", "236",
                "235", "56", "86", "61", "61", "57", "269", "242", "682", "506", "385",
                "53", "599", "357", "420", "243", "45", "253", "1-767", "1-809", "1-829",
                "670", "593", "20", "503", "240", "291", "372", "251", "500", "298", "679",
                "358", "33", "689", "241", "220", "995", "49", "233", "350", "30", "299",
                "1-473", "590", "1-671", "502", "224", "245", "592", "509", "504", "852",
                "36", "354", "91", "62", "98", "964", "353", "972", "39", "1-876", "81",
                "962", "7", "254", "686", "965", "996", "856", "371", "961", "266", "231",
                "218", "423", "370", "352", "853", "389", "261", "265", "60"
            ],
            "phone": "PHONE",
            "select days": "SELECT DAYS",
            "guests no.": "GUESTS NO. (max. 4)",
            "submit": "BOOK",
            "date format": "Y/m/d"
        },
        "tourist-tax-payment": {
            "country code": "en",
            "tab title": "Tourist tax",
            "description": "Choose the payment method you prefer to pay the tourist tax",
            "supported languages": ["EN", "IT"],
            "info": "6 Euros per night at person (no children under 10)",
            "or": "OR",
            "credit card": "CREDIT CARD"
        },
        "thanks": {
            "country code": "en",
            "tab title": "Thank you for booking",
            "description": "Thank you for booking with Garbatella Elegant Apartment",
            "thanks": "THAAANKS!!",
            "info": "WE WILL CONTACT YOU SOON",
            "home page": "BACK TO HOME PAGE"
        }
    },
    "IT": {
        "index": {
            "country code": "it",
            "tab title": "Casa vacanze a Roma",
            "description": "Goditi il Comfort della Tua Casa Vacanze nel Quartiere Garbatella - Il Luogo Ideale per Soggiornare a Roma",
            "tourist tax": "Paga la tassa di soggiorno",
            "supported languages": ["IT", "EN"],
            "header title": "Garbatella Elegant Apartment",
            "header subtitle": "Il luogo ideale per soggiornare a Roma",
            "book button": "PRENOTA ORA",
            "home": "CASA",
            "mq": "100mq",
            "elevator": "Ascensore",
            "living room": "1 Soggiorno spazioso",
            "bed room": "2 Camere matrimoniali",
            "bathroom": "1 Bagno accogliente",
            "kitchen": "1 Cucina accessoriata",
            "terrace": "2 Terrazzi silenziosi",
            "services": "SERVIZI",
            "dishwasher": "Lavastoviglie",
            "fridge": "Frigorifero",
            "microwave oven": "Forno a microonde",
            "toaster": "Tostapane",
            "clothesline": "Stendipanni",
            "laundry machine": "Lavatrice",
            "hairdryer": "Asciugacapelli",
            "netflix": "HDTV da 40 pollici con Netflix",
            "conditioner": "Condizionatore caldo/freddo",
            "wifi": "Wifi Gratuito illimitato",
            "fire alarm": "Allarme antincendio",
            "fire extinguisher": "estintore",
            "first aid kit": "Kit di primo soccorso",
            "neighborhood": "QUARTIERE",
            "supermarket": "Supermercato di fronte casa",
            "garage": "Garage a ore sotto casa",
            "parking": "Parcheggi gratis lungo la via",
            "tobacco shop": "Tabaccheria a 10m",
            "cafe": "Bar nella stessa via a 100m",
            "metro": "Metro garbatella 10min a piedi",
            "city center": "Centro città a meno di 20min",
            "rules": "REGOLE",
            "smoking": "Fumare solo nei terrazzi",
            "no party": "Vietate feste rumorose",
            "contact": "CONTATTO",
            "always available": "l'host è sempre disponibile ad aiutare",
            "more": "DI PIÙ..."
        },
        "more": {
            "country code": "it",
            "tab title": "Casa vacanze a Roma",
            "description": "Goditi il Comfort della Tua Casa Vacanze nel Quartiere Garbatella - Il Luogo Ideale per Soggiornare a Roma",
            "supported languages": ["IT", "EN"],
            "apartment": "Casa",
            "neighborhood": "Quartiere",
            "garbatella": "Cosa vedere alla Garbatella",
            "keep in mind": "Da tenere in mente",
            "apartment text paragraph 1": "L'appartamento è a pochi minuti a piedi dalla stazione “Garbatella” della linea B della metro, in una zona tranquilla e sicura, adatta alle famiglie e con servizio di portineria giornaliero. Per raggiungere il centro di Roma basterà prendere la Metro B e raggiungere in pochi minuti (solo 3 fermate!) la stazione Colosseo, per ritrovarsi proprio di fronte il monumento simbolo della “Città Eterna”.",
            "apartment text paragraph 2": "La casa è situata al settimo piano raggiungibile con ascensore per avere la massima comodità con lo spostamento dei vostri bagagli. L'arredamento e il mobilio sono nuovi, moderni e curati in ogni dettaglio per farti sentire a tuo agio in un ambiente confortevole e rilassante.",
            "apartment text paragraph 3": "La proprietà si compone di ingresso, soggiorno con tavolo da pranzo per 4 persone, con un ampio divano a forma di “L” , TV di 40 pollici con Netflix, condizionatore e terrazzo.",
            "apartment text paragraph 4": "Proseguendo abbiamo due ampie camere da letto queen-size con materasso e cuscini in memory foam che vi permetteranno di dormire comodi e rilassati al fresco o alla temperatura che più preferite grazie ai moderni condizionatori presenti in entrambe le stanze.",
            "apartment text paragraph 5": "Il bagno è nuovo e moderno, con un ampio box doccia, diversi getti d'acqua regolabili alla temperatura che più preferite e dispenser per il bagno schiuma. Sono presenti inoltre asciugamani e teli da doccia, kit di cortesia da Hotel e asciugacapelli. E’ presente, infine, anche la lavatrice.",
            "apartment text paragraph 6": "La cucina spaziosa e abitabile, è completamente attrezzata con tutti i servizi necessari: microonde, forno, macchina del caffè a cialde, tostapane, bollitore, ampio tavolo per 4 persone e attrezzatura varia da cucina.",
            "neighborhood text paragraph 1": "ll quartiere Garbatella è un vero e proprio gioiello nascosto nel cuore di Roma. Situato a sud del centro storico, è un luogo ricco di storia, cultura e autenticità, che cattura immediatamente l'attenzione di chiunque voglia fare una vera esperienza romana.",
            "neighborhood text paragraph 2": "La Garbatella è conosciuta per le sue attività commerciali, le sue case colorate e i cortili interni pittoreschi. Camminare per le sue strade è come immergersi in un'altra epoca, dove tradizione e modernità si fondono in perfetta armonia. Ogni angolo rivela una storia da raccontare e lascia intravedere l'anima di un quartiere che ha fatto molto parlare di sé negli ultimi cento anni. Una delle esperienze imperdibili a Garbatella è sicuramente passeggiare per i suoi vicoli e perdersi tra i suoi giardini segreti. Lungo il percorso, puoi ammirare gli affascinanti murales che decorano le pareti degli edifici, dando vita a una vera e propria galleria a cielo aperto.",
            "neighborhood text paragraph 3": "Inoltre, la Garbatella è famosa per la sua vibrante vita di quartiere con una vasta gamma di caffè, ristoranti, botteghe artigianali e mercati locali. Puoi gustare la cucina tradizionale romana, assaporando autentici piatti come la pasta alla carbonara o la coda alla vaccinara. Non mancano poi le occasioni per trascorrere una serata piacevole con gli amici, sorseggiando un aperitivo in uno dei numerosi locali caratteristici.",
            "neighborhood text paragraph 4": "Anche se si distacca leggermente dai quartieri più famosi di Roma per vivere, la sua atmosfera familiare e l'ospitalità dei suoi abitanti rendono questo luogo una destinazione irresistibile per coloro che desiderano scoprire il vero spirito di Roma.",
            "garbatella text paragraph 1": "Alla Garbatella puoi vedere e fare molte cose, sia dal punto di vista storico che culturale. Se deciderai di abitare qui per un periodo più o meno lungo potrai sia entrare nella storia del quartiere, che vivere la sua atmosfera familiare.",
            "garbatella palladio theatre": "Teatro Palladium",
            "garbatella text paragraph 2": "Si tratta di un antico cinema rionale trasformato in un dinamico centro culturale gestito dall'Università Roma Tre, qui puoi vedere diverse tipologie di film che vanno dal classico al progressivo.",
            "garbatella lovers' staircase": "Scalinata degli innamorati",
            "garbatella text paragraph 3": "Una romantica scalinata fuori dai normali tour che si fanno alla Garbatella e che conduce alla fontana di Carlotta, una fontana dedicata all'ostessa che avrebbe dato il nome al quartiere.",
            "garbatella benedetto brin square": "Piazza Benedetto Brin",
            "garbatella text paragraph 4": "Fu la prima piazza attorno alla quale sorse il nucleo originario della Garbatella, oggi ospita una fontana ed è anche la location di un cinema all’aperto.",
            "garbatella hotels in piazza biffi": "Alberghi di Piazza Biffi",
            "garbatella text paragraph 5": "Tre palazzi colorati costruiti negli anni '30 con uno stile moderno e funzionale, simbolo del cambiamento urbanistico del quartiere.",
            "garbatella church of saints theodore and eurosia": "Chiesa dei Santi Teodoro ed Eurosia",
            "garbatella text paragraph 6": "Nota anche come la “Chiesoletta”, è una piccola chiesa situata in via delle Sette Chiese, è dedicata a due santi legati all'agricoltura ed è anche famosa per esser stata il luogo di incontro tra i santi Filippo Neri e Carlo Borromeo nel 1500, come ricordato da due medaglioni di marmo sulla facciata.",
            "garbatella montemartini museum": "Museo Montemartini",
            "garbatella text paragraph 7": "Un ex impianto termoelettrico che ospita una collezione di sculture antiche, interessante da visitare poiché crea un suggestivo contrasto tra arte e industria.",
            "garbatella basilica of st. paul": "Basilica di San Paolo",
            "garbatella text paragraph 8": "Inoltre, vicino la Garbatella, nel famoso quartiere di San Paolo, è situata una delle quattro basiliche papali di Roma, costruita sul luogo dove sarebbe sepolto l'apostolo Paolo in onore del quale è stato dato il nome alla chiesa.",
            "keep in mind text paragraph 1": "",
            "keep in mind text paragraph 1": "",
            "keep in mind text paragraph 1": ""
        },
        "book-holiday-home": {
            "country code": "it",
            "tab title": "Prenota la tua casa vacanze",
            "description": "Goditi il comfort della tua casa vacanze nel quartiere Garbatella - Il Luogo ideale per soggiornare a Roma",
            "supported languages": ["IT", "EN"],
            "name": "NOME",
            "surname": "COGNOME",
            "email": "EMAIL",
            "codes": [
                "39", "93", "355", "213", "1-684", "376", "244", "1-264", "672", "1-268", "54",
                "374", "297", "61", "43", "994", "1-242", "973", "880", "1-246", "375",
                "32", "501", "229", "1-441", "975", "591", "387", "267", "55", "246",
                "673", "359", "226", "257", "855", "237", "1", "238", "1-345", "236",
                "235", "56", "86", "61", "61", "57", "269", "242", "682", "506", "385",
                "53", "599", "357", "420", "243", "45", "253", "1-767", "1-809", "1-829",
                "670", "593", "20", "503", "240", "291", "372", "251", "500", "298", "679",
                "358", "33", "689", "241", "220", "995", "49", "233", "350", "30", "299",
                "1-473", "590", "1-671", "502", "224", "245", "592", "509", "504", "852",
                "36", "354", "91", "62", "98", "964", "353", "972", "1-876", "81",
                "962", "7", "254", "686", "965", "996", "856", "371", "961", "266", "231",
                "218", "423", "370", "352", "853", "389", "261", "265", "60"
            ],
            "phone": "TELEFONO",
            "select days": "SELEZIONA GIORNI",
            "guests no.": "N° OSPITI (max. 4)",
            "submit": "PRENOTA",
            "date format": "d/m/Y"
        },
        "tourist-tax-payment": {
            "country code": "it",
            "tab title": "Tassa di soggiorno",
            "description": "Scegli il metodo di pagamento che preferisci per pagare la tassa di soggiorno",
            "supported languages": ["IT", "EN"],
            "info": "6 Euro a notte a persona (no minori di 10 Anni)",
            "or": "OPPURE",
            "credit card": "CARTA DI CREDITO"
        },
        "thanks": {
            "country code": "it",
            "tab title": "Grazie per aver prenotato",
            "description": "Ti ringraziamo per aver prenotato con Garbatella Elegant Apartment",
            "thanks": "GRAZIEEE!!",
            "info": "TI CONTATTEREMO A BREVE",
            "home page": "TORNA ALLA HOME PAGE"
        }
    }
}